#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Pipeline Deployment Script
Generated by SageMigrator CLI on 2026-01-13 09:14:50
"""

# Dependency validation
import sys

def check_dependencies():
    """Check if required dependencies are installed"""
    required_packages = [
        ('sagemaker', '2.190.0'),
        ('boto3', '1.26.0')
    ]
    
    missing_packages = []
    
    for package, min_version in required_packages:
        try:
            __import__(package)
        except ImportError:
            missing_packages.append(f"{package}>={min_version}")
    
    if missing_packages:
        print("❌ Missing required dependencies for deployment:")
        for pkg in missing_packages:
            print(f"   - {pkg}")
        print("\n📦 Install missing packages:")
        print(f"   pip install {' '.join(missing_packages)}")
        print("\n💡 Or install from requirements.txt:")
        print("   pip install -r requirements.txt")
        print("\n🔧 For SageMaker SDK v2.x compatibility:")
        print("   pip install 'sagemaker>=2.190.0,<3.0.0' --force-reinstall")
        sys.exit(1)

# Check dependencies before importing
check_dependencies()

import boto3
import json
from pipeline import SagemigratorPipeline


def create_model_package_group():
    """Create model package group if it doesn't exist"""
    sagemaker_client = boto3.client('sagemaker')
    group_name = f"sagemigrator-model-group"
    
    try:
        sagemaker_client.describe_model_package_group(ModelPackageGroupName=group_name)
        print(f"✅ Model package group already exists: {group_name}")
    except sagemaker_client.exceptions.ClientError:
        try:
            sagemaker_client.create_model_package_group(
                ModelPackageGroupName=group_name,
                ModelPackageGroupDescription=f"Model registry for sagemigrator models"
            )
            print(f"✅ Created model package group: {group_name}")
        except Exception as e:
            print(f"❌ Failed to create model package group: {e}")
            raise


def main():
    """Deploy the pipeline"""
    print("🚀 Deploying SageMaker Pipeline...")
    
    try:
        # Create model package group
        create_model_package_group()
        
        # Create and deploy pipeline
        pipeline_manager = SagemigratorPipeline()
        pipeline = pipeline_manager.deploy_pipeline()
        
        print(f"✅ Pipeline deployed successfully: {pipeline.name}")
        print(f"📊 View in console: https://console.aws.amazon.com/sagemaker/home#/pipelines")
        
        # Save pipeline info
        pipeline_info = {
            'pipeline_name': pipeline.name,
            'pipeline_arn': pipeline.pipeline_arn if hasattr(pipeline, 'pipeline_arn') else 'N/A',
            'role': "arn:aws:iam::624178040188:role/sagemigrator-SageMaker-ExecutionRole-dev",
            'bucket': "sagemigrator-sagemaker-bucket-624178040188-us-east-1",
            'accuracy_threshold': 0.85
        }
        
        with open('pipeline_info.json', 'w') as f:
            json.dump(pipeline_info, f, indent=2)
        
        print("📄 Pipeline info saved to pipeline_info.json")
        
        return pipeline
        
    except Exception as e:
        print(f"❌ Pipeline deployment failed: {e}")
        raise


if __name__ == "__main__":
    main()
