#!/bin/bash
# -*- coding: utf-8 -*-
# Preprocessing Wrapper Script for SageMaker Pipeline
# Generated by SageMigrator CLI on 2026-01-13 09:14:50

set -e

echo "Starting preprocessing script..."
echo "Python version: $(python3 --version)"
echo "Current directory: $(pwd)"
echo "Files in /opt/ml/processing/input/: $(ls -la /opt/ml/processing/input/ || echo 'Directory not found')"

# Use the preprocessing script from the input
PREPROCESS_SCRIPT="/opt/ml/processing/input/preprocessing.py"

echo "Running preprocessing script: $PREPROCESS_SCRIPT"
# Run the Python preprocessing script
python3 "$PREPROCESS_SCRIPT"

echo "Preprocessing script completed."
