import json
import boto3
import os

sns = boto3.client('sns')
SNS_TOPIC_ARN = os.environ['SNS_TOPIC_ARN']  # Set by deploy_clickhouse_gateway.py

def lambda_handler(event, context):
    """Lambda handler for ClickHouse analysis notification tool"""
    try:
        # Log the full event for debugging
        print(f"Received event: {json.dumps(event)}")
        
        # Gateway passes arguments directly in the event
        arguments = event if isinstance(event, dict) else {}
        
        return send_analysis_summary(arguments)
            
    except Exception as e:
        print(f"Error: {str(e)}")
        return error_response(str(e))

def send_analysis_summary(arguments):
    """Send analysis summary to SNS topic"""
    try:
        summary = arguments.get('summary', '')
        table_name = arguments.get('table_name', 'Unknown')
        analysis_type = arguments.get('analysis_type', 'General Analysis')
        
        message = f"""
ClickHouse Data Analysis Summary
================================

Table: {table_name}
Analysis Type: {analysis_type}

Summary:
{summary}

Generated by ClickHouse Data Analyst Agent
"""
        
        response = sns.publish(
            TopicArn=SNS_TOPIC_ARN,
            Subject=f'ClickHouse Analysis: {table_name}',
            Message=message
        )
        
        return {
            'statusCode': 200,
            'body': json.dumps({
                'success': True,
                'message': f'Analysis summary sent to SNS topic',
                'message_id': response['MessageId']
            })
        }
        
    except Exception as e:
        return error_response(str(e))

def error_response(message):
    """Standard error response"""
    return {
        'statusCode': 500,
        'body': json.dumps({'success': False, 'error': message})
    }
